
(FORBIDDEN-SYMBOLS :PENALTY 0.9 :SYMBOLS '(COUNT APPLY))

(DEFTEST TEST-FIBER NIL
 (CHECK (EQUALP (FIBER 3) 23) (EQUALP (FIBER 4) 24) (EQUALP (FIBER 5) 25)
  (EQUALP (FIBER 6) 26)))

(DEFUN TEST-Q1 () (TEST-FIBER) (FMAKUNBOUND 'FIBER))

(TEST-Q1)