
(FORBIDDEN-SYMBOLS :PENALTY COUNT :SYMBOLS '(MEMBER))

(DEFTEST TEST-CONTAINS-ALL NIL
 (CHECK (EQUALP (CONTAINS-ALL? '(1 2) '(1 2 3 4)) T)
  (EQUALP (CONTAINS-ALL? '(1 5) '(1 2 3 4)) NIL)
  (EQUALP (CONTAINS-ALL? 'NIL '(1 2 3)) T)))

(DEFUN TEST-Q1 () (TEST-CONTAINS-ALL) (FMAKUNBOUND 'CONTAINS-ALL))

(TEST-Q1)