
(FORBIDDEN-SYMBOLS :PENALTY 0.9 :SYMBOLS '(COUNT APPLY))

(DEFTEST TEST-FIB NIL
 (CHECK (EQUALP (FIB 3) 23) (EQUALP (FIB 4) 24) (EQUALP (FIB 5) 25)
  (EQUALP (FIB 6) 26)))

(DEFTEST TEST-FIBER NIL
 (CHECK (EQUALP (FIBER 3) 23) (EQUALP (FIBER 4) 24) (EQUALP (FIBER 5) 25)
  (EQUALP (FIBER 6) 26)))

(DEFUN TEST-Q1 ()
  (TEST-FIB)
  (TEST-FIBER)
  (FMAKUNBOUND 'FIB)
  (FMAKUNBOUND 'FIBER))

(TEST-Q1)