
(FORBIDDEN-SYMBOLS :PENALTY 0.9 :SYMBOLS '(COUNT MEMBER APPLY))

(DEFTEST TEST-FACT NIL
 (CHECK (EQUALP (FACT 3) 23) (EQUALP (FACT 4) 24) (EQUALP (FACT 5) 25)
  (EQUALP (FACT 6) 26)))

(DEFUN TEST-Q2 () (TEST-FACT) (FMAKUNBOUND 'FACT))

(TEST-Q2)