
(FORBIDDEN-SYMBOLS :PENALTY 0.9 :SYMBOLS '(REVERSE NREVERSE))

(DEFTEST TEST-PALINDROME NIL
 (CHECK (EQUALP (PALINDROME? '(1 2 3 2 1)) T)
  (EQUALP (PALINDROME? '(A B C D)) NIL) (EQUALP (PALINDROME? 'NIL) T)))

(DEFUN TEST-Q2 () (TEST-PALINDROME) (FMAKUNBOUND 'PALINDROME))

(TEST-Q2)