
(FORBIDDEN-SYMBOLS :PENALTY NIL :SYMBOLS 'NIL)

(DEFTEST TEST-REVERSE-LIST NIL
 (CHECK (EQUALP (REVERSE-LIST '(1 2 3 4)) '(4 3 2 1))
  (EQUALP (REVERSE-LIST '(A B C)) '(C B A)) (EQUALP (REVERSE-LIST 'NIL) 'NIL)))

(DEFTEST TEST-PALINDROME NIL
 (CHECK (EQUALP (PALINDROME? '(1 2 3 2 1)) T)
  (EQUALP (PALINDROME? '(A B C D)) NIL) (EQUALP (PALINDROME? 'NIL) T)))

(DEFUN TEST-Q2 ()
  (TEST-REVERSE-LIST)
  (TEST-PALINDROME)
  (FMAKUNBOUND 'REVERSE-LIST)
  (FMAKUNBOUND 'PALINDROME))

(TEST-Q2)