(doc (:title "Intro to Lisp" :folder "~/intro-lisp")
  (q (:title "Exercise" :number 1)
    (wa
      (p "Write a function DOUBLE that doubles a number.")
      (eb (:function double)
        (a (double 2) 4)
        (a (double -1) -2))
      (tcb (:function double)
        (a (double 0) 0)
        (a (double 5) 10)))))