
(DEFPACKAGE #:TEST-RUNTIME
  (:DOCUMENTATION "Creates the code testing runtime")
  (:USE CL :RUTILS "Q1" "Q2")
  (:EXPORT *RESULTS*)
  (:EXPORT *RUNTIME-ERROR*)
  (:EXPORT *LOAD-ERROR*)
  (:EXPORT *CR-WARNING*)
  (:EXPORT *FORBIDDEN-SYMBOLS*)
  (:EXPORT *PENALTY-FORBIDDEN*)
  (:EXPORT :HANDLE-SOLUTION-LOADING))

(DEFPACKAGE "Q1"
  (:DOCUMENTATION "Dedicated package for sandboxing the student's solution")
  (:USE CL CG-SANDBOX)
  (:EXPORT COUNT-OCCURRENCES CONTAINS-ALL))

(DEFPACKAGE "Q2"
  (:DOCUMENTATION "Dedicated package for sandboxing the student's solution")
  (:USE CL CG-SANDBOX)
  (:EXPORT REVERSE-LIST PALINDROME))
