
(FORBIDDEN-SYMBOLS :PENALTY 0.8 :SYMBOLS
 '(REMOVE REMOVE-IF REMOVE-IF-NOT DELETE DELETE-IF DELETE-IF-NOT LOOP LENGTH
          LIST-LENGTH DOTIMES DO DO* TAGBODY DOLIST))

(DEFTEST TEST-SPLIT-EVEN-ODD NIL
 (CHECK (EQUALP (SPLIT-EVEN-ODD '(1 2 3 4 5 6)) '((2 4 6) (1 3 5)))
  (EQUALP (SPLIT-EVEN-ODD '(7 -2 0 8 3)) '((-2 0 8) (7 3)))
  (EQUALP (SPLIT-EVEN-ODD NIL) '(NIL NIL))))

(DEFUN TEST-Q1 () (TEST-SPLIT-EVEN-ODD) (FMAKUNBOUND 'SPLIT-EVEN-ODD))

(TEST-Q1)