
(FORBIDDEN-SYMBOLS :PENALTY 0.8 :SYMBOLS
 '(COUNT COUNT-IF COUNT-IF-NOT REMOVE REMOVE-IF REMOVE-IF-NOT DELETE DELETE-IF
         DELETE-IF-NOT LOOP LENGTH LIST-LENGTH DOTIMES DO DO* TAGBODY DOLIST))

(DEFTEST TEST-COUNT-INTEGERS NIL
 (CHECK
  (EQUALP (COUNT-INTEGERS '(1 2 3 2 4 3 5 1 6 7 8))
          '((1 2) (2 2) (3 2) (4 1) (5 1) (6 1) (7 1) (8 1)))
  (EQUALP (COUNT-INTEGERS '(3 3 3 3)) '((3 4)))
  (EQUALP (COUNT-INTEGERS NIL) NIL)
  (EQUALP (COUNT-INTEGERS '(5 10 15 10 5)) '((5 2) (10 2) (15 1)))))

(DEFUN TEST-Q2 () (TEST-COUNT-INTEGERS) (FMAKUNBOUND 'COUNT-INTEGERS))

(TEST-Q2)