
(FORBIDDEN-SYMBOLS :PENALTY 0.8 :SYMBOLS '(COERCE))

(DEFTEST TEST-UNZIP NIL
 (CHECK (EQUALP (UNZIP #(1 0 4 5 2 1)) '((1 4 2) (0 5 1)))
  (EQUALP (UNZIP #()) '(NIL NIL)) (EQUALP (UNZIP #(7 8)) '((7) (8)))))

(DEFUN TEST-Q3 () (TEST-UNZIP) (FMAKUNBOUND 'UNZIP))

(TEST-Q3)