
(IN-PACKAGE :CL-USER)

(DEFPACKAGE #:SANDBOX
  (:USE :CL :RUTILS)
  (:EXPORT ZIP UNZIP RMV-COUNT COUNT-INTEGERS SPLIT-EVEN-ODD))

(DEFPACKAGE #:TEST-RUNTIME
  (:USE :CL :SANDBOX)
  (:EXPORT *RESULTS*)
  (:EXPORT *RUNTIME-ERROR*)
  (:EXPORT *LOAD-ERROR*)
  (:EXPORT *CR-WARNING*)
  (:EXPORT *FORBIDDEN-SYMBOLS*)
  (:EXPORT *PENALTY-FORBIDDEN*)
  (:EXPORT :HANDLE-SOLUTION-LOADING))
