
(FORBIDDEN-SYMBOLS :PENALTY 0.8 :SYMBOLS '(COUNT MEMBER))

(DEFTEST TEST-COUNT-OCCURRENCES NIL
 (CHECK (EQUALP (COUNT-OCCURRENCES 1 '(1 1 1 1 1)) 5)
  (EQUALP (COUNT-OCCURRENCES 0 '(1 2 3 4)) 0)
  (EQUALP (COUNT-OCCURRENCES 'Z '(A B C Z Z)) 2)))

(DEFUN TEST-Q1 () (TEST-COUNT-OCCURRENCES) (FMAKUNBOUND 'COUNT-OCCURRENCES))

(TEST-Q1)