
(FORBIDDEN-SYMBOLS :PENALTY 0.9 :SYMBOLS '(COUNT APPLY))

(DEFTEST TEST-COUNT-OCCURRENCES NIL
 (CHECK (EQUALP (COUNT-OCCURRENCES 1 '(1 1 1 1 1)) 5)
  (EQUALP (COUNT-OCCURRENCES 0 '(1 2 3 4)) 0)
  (EQUALP (COUNT-OCCURRENCES 'Z '(A B C Z Z)) 2)))

(DEFTEST TEST-CONTAINS-ALL NIL
 (CHECK (EQUALP (CONTAINS-ALL? '(A B) '(A B C D E)) T)
  (EQUALP (CONTAINS-ALL? '(A Z) '(A B C D)) NIL)
  (EQUALP (CONTAINS-ALL? 'NIL 'NIL) T)))

(DEFUN TEST-Q1 ()
  (TEST-COUNT-OCCURRENCES)
  (TEST-CONTAINS-ALL)
  (FMAKUNBOUND 'COUNT-OCCURRENCES)
  (FMAKUNBOUND 'CONTAINS-ALL))

(TEST-Q1)