
(FORBIDDEN-SYMBOLS :PENALTY 0.9 :SYMBOLS '(COUNT MEMBER APPLY))

(DEFTEST TEST-FACT NIL (CHECK (EQUALP (FACT 4) 24) (EQUALP (FACT 12) 222)))

(DEFUN TEST-Q2 () (TEST-FACT) (FMAKUNBOUND 'FACT))

(TEST-Q2)