
(FORBIDDEN-SYMBOLS :PENALTY 0.8 :SYMBOLS '(COUNT MEMBER))

(DEFTEST TEST-CONTAINS-ALL NIL
 (CHECK (EQUALP (CONTAINS-ALL? '(A B) '(A B C D E)) T)
  (EQUALP (CONTAINS-ALL? '(A Z) '(A B C D)) NIL)
  (EQUALP (CONTAINS-ALL? 'NIL 'NIL) T)))

(DEFUN TEST-Q2 () (TEST-CONTAINS-ALL) (FMAKUNBOUND 'CONTAINS-ALL))

(TEST-Q2)