
(FORBIDDEN-SYMBOLS :PENALTY 0.8 :SYMBOLS '(COUNT MEMBER))

(DEFTEST TEST-PALINDROME NIL
 (CHECK (EQUALP (PALINDROME? '(X Y X)) T) (EQUALP (PALINDROME? '(X Y Z)) NIL)
  (EQUALP (PALINDROME? 'NIL) T)))

(DEFUN TEST-Q4 () (TEST-PALINDROME) (FMAKUNBOUND 'PALINDROME))

(TEST-Q4)