;; q1.lisp

(deftest test-graph-traversal ()
  (check
    (equal (let ((g '((1 2))))
	     (graph-traversal g 1))
	   (list 1 2))
    (equal (let ((g '((1 2) (2 3))))
	     (graph-traversal g 1))
	   (list 1 2 3))
    (equal (let ((g '((1 2))))
	     (graph-traversal g 1))
	   (list 1 2))
    (equal (let ((g '((1 2 3) (2 3 4) (3 5))))
	     (graph-traversal g 2))
	   (list 2 3 5))
    (equal (let ((g '((1 1))))
	     (graph-traversal g 1))
	   (list 1))
    (equal (let ((g '((1 2) (2 1))))
	     (graph-traversal g 2))
	   (list 2 1))
    (equal (let ((g '((1 2) (2 4 3))))
	     (graph-traversal g 2))
	   (list 2 4))
    (equal (let ((g '((1 2 3) (2 3) (3 4 2))))
             (graph-traversal g 4))
           (list 4))
    (equal (let ((g '((1 2 4) (2 3) (3 4 2))))
             (graph-traversal g 2))
           (list 2 3 4))))


(defun test-q1 ()
  (test-graph-traversal)
  (fmakunbound 'graph-traversal))

(test-q1)
